USE quanlybanhang;

-- [12]
SELECT SOHD
FROM CTHD
WHERE (
          MASP = 'BB01'
          OR MASP = 'BB02'
      )
      AND SL
      BETWEEN 10 AND 20;

-- [13]
SELECT SOHD
FROM CTHD
WHERE SL
      BETWEEN 10 AND 20
      AND MASP = 'BB01'
      AND SOHD IN
          (
              SELECT SOHD FROM CTHD WHERE MASP = 'BB02'
          );

-- [14]
SELECT MASP,
       TENSP
FROM dbo.SANPHAM S
WHERE NUOCSX = 'Trung Quoc'
UNION
SELECT S.MASP,
       S.TENSP
FROM dbo.SANPHAM S
    INNER JOIN dbo.CTHD C
        ON C.MASP = S.MASP
    INNER JOIN dbo.HOADON H
        ON C.SOHD = H.SOHD
WHERE H.NGHD = '1/1/2007';

-- [15]
SELECT S.MASP,
       S.TENSP
FROM dbo.SANPHAM S
WHERE NOT EXISTS
(
    SELECT * FROM dbo.CTHD C WHERE S.MASP = C.MASP
);

-- [16]
SELECT MASP,
       TENSP
FROM dbo.SANPHAM
WHERE MASP IN
      (
          SELECT MASP
          FROM dbo.SANPHAM
          EXCEPT
          (SELECT MASP
           FROM dbo.CTHD
           WHERE SOHD IN
                 (
                     SELECT SOHD FROM dbo.HOADON WHERE YEAR(NGHD) = 2006
                 ))
      );

-- [17]
SELECT MASP,
       TENSP
FROM dbo.SANPHAM
WHERE NUOCSX = 'Trung Quoc'
      AND MASP IN
          (
              SELECT MASP
              FROM dbo.SANPHAM
              EXCEPT
              (SELECT MASP
               FROM dbo.CTHD
               WHERE SOHD IN
                     (
                         SELECT SOHD FROM dbo.HOADON WHERE YEAR(NGHD) = 2006
                     ))
          );

-- [18]
SELECT H.SOHD
FROM dbo.HOADON H
    INNER JOIN dbo.CTHD C
        ON H.SOHD = C.SOHD
    INNER JOIN dbo.SANPHAM S
        ON S.MASP = C.MASP
WHERE S.NUOCSX = 'Singapore'
GROUP BY H.SOHD
HAVING COUNT(DISTINCT S.MASP) =
(
    SELECT COUNT(DISTINCT MASP)FROM dbo.SANPHAM WHERE NUOCSX = 'Singapore'
);

-- [19]
SELECT H.SOHD
FROM dbo.HOADON H
    INNER JOIN dbo.CTHD C
        ON H.SOHD = C.SOHD
    INNER JOIN dbo.SANPHAM S
        ON C.MASP = S.MASP
WHERE YEAR(H.NGHD) = 2006
      AND S.NUOCSX = 'Singapore'
GROUP BY H.SOHD
HAVING COUNT(DISTINCT S.MASP) =
(
    SELECT COUNT(DISTINCT MASP)FROM dbo.SANPHAM WHERE NUOCSX = 'Singapore'
);


-- [20]
SELECT COUNT(SOHD)
FROM dbo.HOADON
WHERE MAKH IS NULL;

-- [21]
SELECT COUNT(DISTINCT (C.MASP)) AS SOSANPHAM
FROM dbo.CTHD C
    INNER JOIN dbo.HOADON H
        ON H.SOHD = C.SOHD
WHERE YEAR(H.NGHD) = 2006;

-- [22]
SELECT MAX(TRIGIA) AS CAONHAT,
       MIN(TRIGIA) AS THAPNHAT
FROM dbo.HOADON;

-- [23]
SELECT AVG(TRIGIA) AS TRUNGBINH
FROM dbo.HOADON
WHERE YEAR(NGHD) = 2006;

-- [24]
SELECT SUM(TRIGIA)
FROM dbo.HOADON
WHERE YEAR(NGHD) = 2006;